const FINISHERS = [
  {
    "id": "F1",
    "no": 1,
    "name": "Jasmine Fate Albarico",
    "surname": "Albarico",
    "company": "Infosoft",
    "site": "Cebu",
    "group": "G3 - ViSayaS",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 52.1,
    "goalKm": 50,
    "pin": "Albarico1995",
    "source": "finisher",
    "filename": "F1_01_STRIDE_Jasmine-Fate-Albarico.png"
  },
  {
    "id": "F2",
    "no": 2,
    "name": "Kimberly Bano",
    "surname": "Bano",
    "company": "Infosoft",
    "site": "Cebu",
    "group": "G3 - ViSayaS",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": "2nd Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 94.89,
    "goalKm": 50,
    "pin": "Bano1995",
    "source": "finisher",
    "filename": "F2_02_STRIDE_Kimberly-Bano.png"
  },
  {
    "id": "F3",
    "no": 3,
    "name": "Luzmae Ann Batle",
    "surname": "Batle",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 51.7,
    "goalKm": 50,
    "pin": "Batle2001",
    "source": "finisher",
    "filename": "F3_03_STRIDE_Luzmae-Ann-Batle.png"
  },
  {
    "id": "F4",
    "no": 4,
    "name": "Julia Rovie De Guia",
    "surname": "De Guia",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G4 - Mindanao",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 51.99,
    "goalKm": 50,
    "pin": "DeGuia2002",
    "source": "finisher",
    "filename": "F4_04_STRIDE_Julia-Rovie-De-Guia.png"
  },
  {
    "id": "F5",
    "no": 5,
    "name": "Divine Fabon",
    "surname": "Fabon",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": "3rd Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 59,
    "goalKm": 50,
    "pin": "Fabon2001",
    "source": "finisher",
    "filename": "F5_05_STRIDE_Divine-Fabon.png"
  },
  {
    "id": "F6",
    "no": 6,
    "name": "Maria Ni\u00f1a Melrose Jumao-as",
    "surname": "Jumao-as",
    "company": "Kassatech",
    "site": "Davao",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 70.8,
    "goalKm": 50,
    "pin": "Jumao-as1977",
    "source": "finisher",
    "filename": "F6_06_STRIDE_Maria-Ni-a-Melrose-Jumao-as.png"
  },
  {
    "id": "F7",
    "no": 7,
    "name": "Johanson Medil",
    "surname": "Medil",
    "company": "Infosoft",
    "site": "Cebu",
    "group": "G6 - KaSSa",
    "sex": "M",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": "3rd Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 56.3,
    "goalKm": 50,
    "pin": "Medil1995",
    "source": "finisher",
    "filename": "F7_07_STRIDE_Johanson-Medil.png"
  },
  {
    "id": "F8",
    "no": 8,
    "name": "Cherry Medrina",
    "surname": "Medrina",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G4 - Mindanao",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 53.55,
    "goalKm": 50,
    "pin": "Medrina2002",
    "source": "finisher",
    "filename": "F8_08_STRIDE_Cherry-Medrina.png"
  },
  {
    "id": "F9",
    "no": 9,
    "name": "Duke Ian Pastor",
    "surname": "Pastor",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G4 - Mindanao",
    "sex": "M",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": "2nd Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 53.29,
    "goalKm": 50,
    "pin": "Pastor1999",
    "source": "finisher",
    "filename": "F9_09_STRIDE_Duke-Ian-Pastor.png"
  },
  {
    "id": "F10",
    "no": 10,
    "name": "Chris Patong",
    "surname": "Patong",
    "company": "Dimensions",
    "site": "Manila",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "M",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": "1st Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 71.6,
    "goalKm": 50,
    "pin": "Patong1977",
    "source": "finisher",
    "filename": "F10_10_STRIDE_Chris-Patong.png"
  },
  {
    "id": "F11",
    "no": 11,
    "name": "Marianita Quimson",
    "surname": "Quimson",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": "1st Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 81.1,
    "goalKm": 50,
    "pin": "Quimson1978",
    "source": "finisher",
    "filename": "F11_11_STRIDE_Marianita-Quimson.png"
  },
  {
    "id": "F12",
    "no": 12,
    "name": "Chanda Rosales Salcedo",
    "surname": "Salcedo",
    "company": "Dimensions",
    "site": "Davao",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "F",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 53.04,
    "goalKm": 50,
    "pin": "Salcedo1996",
    "source": "finisher",
    "filename": "F12_12_STRIDE_Chanda-Rosales-Salcedo.png"
  },
  {
    "id": "F13",
    "no": 13,
    "name": "Raye Vanne Sibal",
    "surname": "Sibal",
    "company": "Dimensions",
    "site": "Davao",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "M",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 55.4,
    "goalKm": 50,
    "pin": "Sibal1993",
    "source": "finisher",
    "filename": "F13_13_STRIDE_Raye-Vanne-Sibal.png"
  },
  {
    "id": "F14",
    "no": 14,
    "name": "King Walter Mark Anthony Alicer",
    "surname": "Alicer",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G1 - Luzon 1",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 124.69,
    "goalKm": 100,
    "pin": "Alicer1998",
    "source": "finisher",
    "filename": "F14_14_STRIDE_King-Walter-Mark-Anthony-Alicer.png"
  },
  {
    "id": "F15",
    "no": 15,
    "name": "Edward Anglo",
    "surname": "Anglo",
    "company": "Kassatech",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 106.4,
    "goalKm": 100,
    "pin": "Anglo1991",
    "source": "finisher",
    "filename": "F15_15_STRIDE_Edward-Anglo.png"
  },
  {
    "id": "F16",
    "no": 16,
    "name": "Joyce Carniyan",
    "surname": "Carniyan",
    "company": "Acceltech",
    "site": "Manila",
    "group": "G5 - Acceltech",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": "2nd Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 170.45,
    "goalKm": 100,
    "pin": "Carniyan1999",
    "source": "finisher",
    "filename": "F16_16_STRIDE_Joyce-Carniyan.png"
  },
  {
    "id": "F17",
    "no": 17,
    "name": "Shaira Mae Cereno",
    "surname": "Cereno",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G2 - Luzon 2",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 101.2,
    "goalKm": 100,
    "pin": "Cereno1995",
    "source": "finisher",
    "filename": "F17_17_STRIDE_Shaira-Mae-Cereno.png"
  },
  {
    "id": "F18",
    "no": 18,
    "name": "Junald John Clenista",
    "surname": "Clenista",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G1 - Luzon 1",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": "3rd Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 159.96,
    "goalKm": 100,
    "pin": "Clenista1996",
    "source": "finisher",
    "filename": "F18_18_STRIDE_Junald-John-Clenista.png"
  },
  {
    "id": "F19",
    "no": 19,
    "name": "Claire Cristobal",
    "surname": "Cristobal",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G1 - Luzon 1",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": "1st Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 168.6,
    "goalKm": 100,
    "pin": "Cristobal1996",
    "source": "finisher",
    "filename": "F19_19_STRIDE_Claire-Cristobal.png"
  },
  {
    "id": "F20",
    "no": 20,
    "name": "Lyn De Vera",
    "surname": "De Vera",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G3 - ViSayaS",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": "3rd Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 300.77,
    "goalKm": 100,
    "pin": "DeVera1997",
    "source": "finisher",
    "filename": "F20_20_STRIDE_Lyn-De-Vera.png"
  },
  {
    "id": "F21",
    "no": 21,
    "name": "Schyrien Escudero",
    "surname": "Escudero",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G1 - Luzon 1",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 130.2,
    "goalKm": 100,
    "pin": "Escudero1996",
    "source": "finisher",
    "filename": "F21_21_STRIDE_Schyrien-Escudero.png"
  },
  {
    "id": "F22",
    "no": 22,
    "name": "James Edward Golla",
    "surname": "Golla",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G2 - Luzon 2",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 105.79,
    "goalKm": 100,
    "pin": "Golla1979",
    "source": "finisher",
    "filename": "F22_22_STRIDE_James-Edward-Golla.png"
  },
  {
    "id": "F23",
    "no": 23,
    "name": "Kolline Maceda",
    "surname": "Maceda",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 250.9,
    "goalKm": 100,
    "pin": "Maceda1998",
    "source": "finisher",
    "filename": "F23_23_STRIDE_Kolline-Maceda.png"
  },
  {
    "id": "F24",
    "no": 24,
    "name": "Xanders Olarte",
    "surname": "Olarte",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": "1st Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 108.9,
    "goalKm": 100,
    "pin": "Olarte1991",
    "source": "finisher",
    "filename": "F24_24_STRIDE_Xanders-Olarte.png"
  },
  {
    "id": "F25",
    "no": 25,
    "name": "Alexis Parrera",
    "surname": "Parrera",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 162.5,
    "goalKm": 100,
    "pin": "Parrera2000",
    "source": "finisher",
    "filename": "F25_25_STRIDE_Alexis-Parrera.png"
  },
  {
    "id": "F26",
    "no": 26,
    "name": "Michelle Angelika Tale\u00f1o",
    "surname": "Tale\u00f1o",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 101.3,
    "goalKm": 100,
    "pin": "Tale\u00f1o2002",
    "source": "finisher",
    "filename": "F26_26_STRIDE_Michelle-Angelika-Tale-o.png"
  },
  {
    "id": "F27",
    "no": 27,
    "name": "Glazel Mei Anne Teves",
    "surname": "Teves",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G4 - Mindanao",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 104.71,
    "goalKm": 100,
    "pin": "Teves2000",
    "source": "finisher",
    "filename": "F27_27_STRIDE_Glazel-Mei-Anne-Teves.png"
  },
  {
    "id": "F28",
    "no": 28,
    "name": "Princess Nicole Tizon",
    "surname": "Tizon",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 100,
    "goalKm": 100,
    "pin": "Tizon2006",
    "source": "finisher",
    "filename": "F28_28_STRIDE_Princess-Nicole-Tizon.png"
  },
  {
    "id": "F29",
    "no": 29,
    "name": "Joshua Villame",
    "surname": "Villame",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G4 - Mindanao",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 131.16,
    "goalKm": 100,
    "pin": "Villame1995",
    "source": "finisher",
    "filename": "F29_29_STRIDE_Joshua-Villame.png"
  },
  {
    "id": "F30",
    "no": 30,
    "name": "Novie Alfred Villanueva",
    "surname": "Villanueva",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G1 - Luzon 1",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": "2nd Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 302.34,
    "goalKm": 100,
    "pin": "Villanueva2001",
    "source": "finisher",
    "filename": "F30_30_STRIDE_Novie-Alfred-Villanueva.png"
  },
  {
    "id": "F31",
    "no": 31,
    "name": "Jhan Vincent Villasin",
    "surname": "Villasin",
    "company": "Acceltech",
    "site": "Davao",
    "group": "G5 - Acceltech",
    "sex": "M",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 111.4,
    "goalKm": 100,
    "pin": "Villasin1993",
    "source": "finisher",
    "filename": "F31_31_STRIDE_Jhan-Vincent-Villasin.png"
  },
  {
    "id": "F32",
    "no": 32,
    "name": "Arnel Castro",
    "surname": "Castro",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": "1st Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 1176.51,
    "goalKm": 300,
    "pin": "Castro1981",
    "source": "finisher",
    "filename": "F32_32_STRIDE_Arnel-Castro.png"
  },
  {
    "id": "F33",
    "no": 33,
    "name": "Lourdes Fajardo",
    "surname": "Fajardo",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G1 - Luzon 1",
    "sex": "F",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": "2nd Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 534.28,
    "goalKm": 300,
    "pin": "Fajardo1975",
    "source": "finisher",
    "filename": "F33_33_STRIDE_Lourdes-Fajardo.png"
  },
  {
    "id": "F34",
    "no": 34,
    "name": "John Pol Flores",
    "surname": "Flores",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G1 - Luzon 1",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": "3rd Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 333.7,
    "goalKm": 300,
    "pin": "Flores1998",
    "source": "finisher",
    "filename": "F34_34_STRIDE_John-Pol-Flores.png"
  },
  {
    "id": "F35",
    "no": 35,
    "name": "Hazel Grace Guan",
    "surname": "Guan",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": null,
    "awardColor": null,
    "totalKm": 301.18,
    "goalKm": 300,
    "pin": "Guan1999",
    "source": "finisher",
    "filename": "F35_35_STRIDE_Hazel-Grace-Guan.png"
  },
  {
    "id": "F36",
    "no": 36,
    "name": "Mario Eduardo Moll",
    "surname": "Moll",
    "company": "Acceltech",
    "site": "Manila",
    "group": "G5 - Acceltech",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": null,
    "awardColor": null,
    "totalKm": 303.84,
    "goalKm": 300,
    "pin": "Moll1980",
    "source": "finisher",
    "filename": "F36_36_STRIDE_Mario-Eduardo-Moll.png"
  },
  {
    "id": "F37",
    "no": 37,
    "name": "Erick Palaypayon",
    "surname": "Palaypayon",
    "company": "Kassatech",
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": "2nd Place (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 578.7,
    "goalKm": 300,
    "pin": "Palaypayon1982",
    "source": "finisher",
    "filename": "F37_37_STRIDE_Erick-Palaypayon.png"
  },
  {
    "id": "F38",
    "no": 38,
    "name": "Morris Raymond Perdon",
    "surname": "Perdon",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G1 - Luzon 1",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": null,
    "awardColor": null,
    "totalKm": 376.5,
    "goalKm": 300,
    "pin": "Perdon1981",
    "source": "finisher",
    "filename": "F38_38_STRIDE_Morris-Raymond-Perdon.png"
  },
  {
    "id": "F39",
    "no": 39,
    "name": "Mylene Ponsica",
    "surname": "Ponsica",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G2 - Luzon 2",
    "sex": "F",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": "3rd Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 500,
    "goalKm": 300,
    "pin": "Ponsica1983",
    "source": "finisher",
    "filename": "F39_39_STRIDE_Mylene-Ponsica.png"
  },
  {
    "id": "F40",
    "no": 40,
    "name": "Anne Jeline Salandanan",
    "surname": "Salandanan",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G1 - Luzon 1",
    "sex": "F",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": "1st Place (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 1030.5,
    "goalKm": 300,
    "pin": "Salandanan1999",
    "source": "finisher",
    "filename": "F40_40_STRIDE_Anne-Jeline-Salandanan.png"
  },
  {
    "id": "F41",
    "no": 41,
    "name": "Russell Dave Samson",
    "surname": "Samson",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G3 - ViSayaS",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": null,
    "awardColor": null,
    "totalKm": 300.04,
    "goalKm": 300,
    "pin": "Samson1976",
    "source": "finisher",
    "filename": "F41_41_STRIDE_Russell-Dave-Samson.png"
  },
  {
    "id": "F42",
    "no": 42,
    "name": "Sep Ventura",
    "surname": "Ventura",
    "company": "Acceltech",
    "site": "Manila",
    "group": "G5 - Acceltech",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": null,
    "awardColor": null,
    "totalKm": 308,
    "goalKm": 300,
    "pin": "Ventura1986",
    "source": "finisher",
    "filename": "F42_42_STRIDE_Sep-Ventura.png"
  },
  {
    "id": "F43",
    "no": 43,
    "name": "Mary Ann Zambale",
    "surname": "Zambale",
    "company": "Infosoft",
    "site": "Manila",
    "group": "G8 - ExeComm",
    "sex": "F",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": null,
    "awardColor": null,
    "totalKm": 361.76,
    "goalKm": 300,
    "pin": "Zambale1973",
    "source": "finisher",
    "filename": "F43_43_STRIDE_Mary-Ann-Zambale.png"
  },
  {
    "id": "F44",
    "no": 44,
    "name": "Charles Gil Daitol",
    "surname": "Daitol",
    "company": "Dimensions",
    "site": "Davao",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "M",
    "category": "RIDE",
    "level": "400 KM \u2014 Ascend level",
    "levelColor": "#FFCC00",
    "award": null,
    "awardColor": null,
    "totalKm": 925.18,
    "goalKm": 400,
    "pin": "Daitol1992",
    "source": "finisher",
    "filename": "F44_44_RIDE_Charles-Gil-Daitol.png"
  },
  {
    "id": "F45",
    "no": 45,
    "name": "Ivy Moll",
    "surname": "Moll",
    "company": "Acceltech",
    "site": "Manila",
    "group": "G5 - Acceltech",
    "sex": "F",
    "category": "RIDE",
    "level": "400 KM \u2014 Ascend level",
    "levelColor": "#FFCC00",
    "award": "Winner (Female Category)",
    "awardColor": "#FF5050",
    "totalKm": 403.8,
    "goalKm": 400,
    "pin": "Moll1981",
    "source": "finisher",
    "filename": "F45_45_RIDE_Ivy-Moll.png"
  },
  {
    "id": "F46",
    "no": 46,
    "name": "Ryan Serdan",
    "surname": "Serdan",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G1 - Luzon 1",
    "sex": "M",
    "category": "RIDE",
    "level": "400 KM \u2014 Ascend level",
    "levelColor": "#FFCC00",
    "award": null,
    "awardColor": null,
    "totalKm": 492.64,
    "goalKm": 400,
    "pin": "Serdan2000",
    "source": "finisher",
    "filename": "F46_46_RIDE_Ryan-Serdan.png"
  },
  {
    "id": "F47",
    "no": 47,
    "name": "Reno Roy Sorima",
    "surname": "Sorima",
    "company": "Dimensions",
    "site": "Davao",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "M",
    "category": "RIDE",
    "level": "400 KM \u2014 Ascend level",
    "levelColor": "#FFCC00",
    "award": "Winner (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 610.1,
    "goalKm": 400,
    "pin": "Sorima1995",
    "source": "finisher",
    "filename": "F47_47_RIDE_Reno-Roy-Sorima.png"
  },
  {
    "id": "F48",
    "no": 48,
    "name": "Ephraim Nick Subillaga",
    "surname": "Subillaga",
    "company": "Dimensions",
    "site": "Davao",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "M",
    "category": "RIDE",
    "level": "400 KM \u2014 Ascend level",
    "levelColor": "#FFCC00",
    "award": null,
    "awardColor": null,
    "totalKm": 566.28,
    "goalKm": 400,
    "pin": "Subillaga1995",
    "source": "finisher",
    "filename": "F48_48_RIDE_Ephraim-Nick-Subillaga.png"
  },
  {
    "id": "F49",
    "no": 49,
    "name": "Sep Ventura",
    "surname": "Ventura",
    "company": "Acceltech",
    "site": "Manila",
    "group": "G5 - Acceltech",
    "sex": "M",
    "category": "RIDE",
    "level": "400 KM \u2014 Ascend level",
    "levelColor": "#FFCC00",
    "award": null,
    "awardColor": null,
    "totalKm": 415.7,
    "goalKm": 400,
    "pin": "Ventura1986",
    "source": "finisher",
    "filename": "F49_49_RIDE_Sep-Ventura.png"
  },
  {
    "id": "F50",
    "no": 50,
    "name": "Charlie Magne Dano",
    "surname": "Dano",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G4 - Mindanao",
    "sex": "M",
    "category": "RIDE",
    "level": "750 KM \u2014 Enduro level",
    "levelColor": "#FF9966",
    "award": null,
    "awardColor": null,
    "totalKm": 759.68,
    "goalKm": 750,
    "pin": "Dano1994",
    "source": "finisher",
    "filename": "F50_50_RIDE_Charlie-Magne-Dano.png"
  },
  {
    "id": "F51",
    "no": 51,
    "name": "Mario Eduardo Moll",
    "surname": "Moll",
    "company": "Acceltech",
    "site": "Manila",
    "group": "G5 - Acceltech",
    "sex": "M",
    "category": "RIDE",
    "level": "750 KM \u2014 Enduro level",
    "levelColor": "#FF9966",
    "award": null,
    "awardColor": null,
    "totalKm": 1175.9,
    "goalKm": 750,
    "pin": "Moll1980",
    "source": "finisher",
    "filename": "F51_51_RIDE_Mario-Eduardo-Moll.png"
  },
  {
    "id": "F52",
    "no": 52,
    "name": "Alfonso Torres",
    "surname": "Torres",
    "company": "Infosoft",
    "site": "Davao",
    "group": "G7 - Dimensions + Cross BU",
    "sex": "M",
    "category": "RIDE",
    "level": "750 KM \u2014 Enduro level",
    "levelColor": "#FF9966",
    "award": "Winner (Male Category)",
    "awardColor": "#FF5050",
    "totalKm": 1261.02,
    "goalKm": 750,
    "pin": "Torres1981",
    "source": "finisher",
    "filename": "F52_52_RIDE_Alfonso-Torres.png"
  },
  {
    "id": "G1",
    "no": 1,
    "name": "John Carlo Maglaque",
    "surname": "Maglaque",
    "company": null,
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "M",
    "category": "STRIDE",
    "level": "50 KM \u2014 Challenger level",
    "levelColor": "#00CC00",
    "award": null,
    "awardColor": null,
    "totalKm": 52.14,
    "goalKm": 50,
    "pin": "Maglaque50",
    "source": "guest",
    "filename": "G1_01_STRIDE_John-Carlo-Maglaque.png"
  },
  {
    "id": "G2",
    "no": 2,
    "name": "Marianne Bueno",
    "surname": "Bueno",
    "company": null,
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 119.53,
    "goalKm": 100,
    "pin": "Bueno100",
    "source": "guest",
    "filename": "G2_02_STRIDE_Marianne-Bueno.png"
  },
  {
    "id": "G3",
    "no": 3,
    "name": "Airish Noreen Ledda",
    "surname": "Ledda",
    "company": null,
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 138.36,
    "goalKm": 100,
    "pin": "Ledda100",
    "source": "guest",
    "filename": "G3_03_STRIDE_Airish-Noreen-Ledda.png"
  },
  {
    "id": "G4",
    "no": 4,
    "name": "Angel Reign Manuel",
    "surname": "Manuel",
    "company": null,
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "F",
    "category": "STRIDE",
    "level": "100 KM \u2014 Igniter level",
    "levelColor": "#0099FF",
    "award": null,
    "awardColor": null,
    "totalKm": 101.2,
    "goalKm": 100,
    "pin": "Manuel100",
    "source": "guest",
    "filename": "G4_04_STRIDE_Angel-Reign-Manuel.png"
  },
  {
    "id": "G5",
    "no": 5,
    "name": "Sky Yadav",
    "surname": "Yadav",
    "company": null,
    "site": "Manila",
    "group": "G6 - KaSSa",
    "sex": "M",
    "category": "STRIDE",
    "level": "300 KM \u2014 Elite level",
    "levelColor": "#9900CC",
    "award": null,
    "awardColor": null,
    "totalKm": 388.5,
    "goalKm": 300,
    "pin": "Yadav300",
    "source": "guest",
    "filename": "G5_05_STRIDE_Sky-Yadav.png"
  }
];
